services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node_server
    restart: on-failure
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app # bind‑mount your source
      - /app/node_modules # keep container node_modules separate from host
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: {}
